# Generated by Django 4.1.1 on 2023-04-02 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('img', models.CharField(max_length=250)),
                ('bio', models.TextField(max_length=500)),
            ],
        ),
    ]
