# Generated by Django 4.2 on 2023-08-12 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_alter_teammember_bio_alter_teammember_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Retreat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('date', models.CharField(max_length=100)),
                ('image', models.CharField(max_length=250)),
                ('registrationURL', models.CharField(max_length=200)),
            ],
        ),
    ]
