# Generated by Django 4.1.1 on 2023-08-13 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_rename_date_retreat_dates_retreat_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='retreat',
            name='description',
            field=models.TextField(blank=True, max_length=2500, null=True),
        ),
    ]
