# Generated by Django 4.1.1 on 2024-02-22 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_alter_retreat_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('url', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True, max_length=1200, null=True)),
            ],
        ),
    ]
